---
name: "Setup mark"
author: Yevhen Fabizhevskyi
description: "This action installs mark CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "mark version."
    required: false
    default: "9.11.1"
runs:
  using: "composite"
  steps:
    - name: Install kovetskiy/mark
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: ./install-mark.sh "${INPUT_VERSION}"
      shell: sh
      working-directory: ${{ github.action_path }}/src
