---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - src/**
      - action.yml

defaults:
  run:
    shell: sh

jobs:
  setup-mark:
    name: Setup mark
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        version: ["latest", "10.0.1", "10.0.0", "9.13.0", "9.12.0", "9.11.1"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup mark
        uses: ./
        with:
          version: "${{ matrix.version }}"
      - name: Print version
        run: mark --version
