---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request: {}

defaults:
  run:
    shell: sh

jobs:
  setup-mark:
    name: Setup mark
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        version: ["9.11.1", "9.11.0", "9.10.1", "9.10.0", "9.9.0"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup mark
        uses: ./
        with:
          version: "${{ matrix.version }}"
      - name: Print version
        run: mark --version
