---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - src/**
      - action.yml

defaults:
  run:
    shell: sh

jobs:
  get-versions:
    name: Get 5 latest versions
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      versions: ${{ steps.prepare-list.outputs.versions }}
    steps:
      - name: Prepare list
        id: prepare-list
        run: |
          url="https://api.github.com/repos/kovetskiy/mark/releases"
          versions=$(curl -s "${url}" | jq -c '[.[0:5][].tag_name] | . += ["latest"]')
          echo "versions=${versions}" >> "$GITHUB_OUTPUT"
  setup-mark:
    name: Setup mark
    needs: [get-versions]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup mark
        uses: ./
        with:
          version: "${{ matrix.version }}"
      - name: Print version
        run: mark --version
